### PR TITLE
Add Printemps

### LINKED ISSUE #107: Add Printemps  - Commercial Terms
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://contribute.opentermsarchive.org/fr/service?destination=OpenTermsArchive%2Fdeclarations-france&documentType=Commercial%20Terms&name=Printemps%20&removedCss[]=.main-breadcrumb&selectedCss[]=.content-page&step=2&url=https%3A%2F%2Fwww.printemps.com%2Ffr%2Ffr%2Fconditions-generales-vente-utilisation&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Printemps ",
  "documents": {
    "Commercial Terms": {
      "fetch": "https://www.printemps.com/fr/fr/conditions-generales-vente-utilisation",
      "select": [
        ".content-page"
      ],
      "remove": [
        ".main-breadcrumb"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Printemps .json`

### LINKED ISSUE #108: Add Printemps  - Privacy Policy
New service addition requested through the contribution tool

You can see the work done by the awesome contributor here:
https://contribute.opentermsarchive.org/fr/service?destination=OpenTermsArchive%2Fdeclarations-france&documentType=Privacy%20Policy&name=Printemps%20&removedCss[]=.main-breadcrumb&selectedCss[]=.content-page&step=2&url=https%3A%2F%2Fwww.printemps.com%2Ffr%2Ffr%2Fprotection-donnees-personnelles&expertMode=true

Or you can see the JSON generated here:
```json
{
  "name": "Printemps ",
  "documents": {
    "Privacy Policy": {
      "fetch": "https://www.printemps.com/fr/fr/protection-donnees-personnelles",
      "select": [
        ".content-page"
      ],
      "remove": [
        ".main-breadcrumb"
      ]
    }
  }
}
```

You will need to create the following file in the root of the project: `services/Printemps .json`

### PR DESCRIPTION
**Pull request by martinratinaud**
closes #108 closes #107

### CODE REVIEW

**Comment by martinratinaud** [comment]
@clementbiron I need some adice on that because I get that kind of content when crawled

```
Conditions g�n�rales d'utilisation et de vente
==============================================

Pr�ambule

L'enseigne Printemps.com (� **la Soci�t�** �) dispose d'un site internet de e-commerce, accessible � l'adresse [www.printemps.com](https://www.printemps.com/fr/fr) (� **le Site** �).
```

I'm not sure if it is on my machine only.

Did you ever got that kind of problem?

**Comment by clementbiron** [comment]
I get the same error and I have never encountered this type.
The snapshot is bad :

image

We can't merge for now.

**Comment by martinratinaud** [comment]
maybe @Ndpnt has some insights on this? or @MattiSG

**Comment by clementbiron** [comment]
`<meta http-equiv="[Content-Type]()" content="[text/html; charset=ISO-8859-1]()" />`

**Comment by martinratinaud** [comment]
This is indeed a weird meta

Looks like a markdown link?

**Comment by MattiSG** [comment]
Clearly an encoding issue. The meta tag tells us the content should be in ISO-Latin-1, and it is probably interpreted as UTF-8 because it is malformed. Is this the same both with and without `executeClientScripts`?

**Comment by clementbiron** [comment]
No more encoding issue with `executeClientScripts:true`, thanks @MattiSG 

I pushed the fix and i think we can merge now.

image

**Review by clementbiron — APPROVED** [review]

**Comment by MattiSG** [comment]
I love how this exercise makes us discover all sort of ugly things on the web… What a great idea to dynamically re-encode textual content 🙃

**Pull request merged**
